// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjRZbs66KnMzku1OyPyHq5PYHR3p9oDY',
    appId: '1:660147494084:web:427587829217e68b39fd91',
    messagingSenderId: '660147494084',
    projectId: 'dadnv2',
    authDomain: 'dadnv2.firebaseapp.com',
    storageBucket: 'dadnv2.firebasestorage.app',
    measurementId: 'G-TE26X7SSVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrAGwwKNU_cc0zzIL0SSlT_d7e9ZFv8A',
    appId: '1:660147494084:android:691384d896ceabb439fd91',
    messagingSenderId: '660147494084',
    projectId: 'dadnv2',
    storageBucket: 'dadnv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDqp1BpTicozo83oLwR7Y6zyZG34pjHSQ',
    appId: '1:660147494084:ios:6aedf078e433b66339fd91',
    messagingSenderId: '660147494084',
    projectId: 'dadnv2',
    storageBucket: 'dadnv2.firebasestorage.app',
    iosBundleId: 'com.example.dadnv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDqp1BpTicozo83oLwR7Y6zyZG34pjHSQ',
    appId: '1:660147494084:ios:6aedf078e433b66339fd91',
    messagingSenderId: '660147494084',
    projectId: 'dadnv2',
    storageBucket: 'dadnv2.firebasestorage.app',
    iosBundleId: 'com.example.dadnv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjRZbs66KnMzku1OyPyHq5PYHR3p9oDY',
    appId: '1:660147494084:web:1ad88878a54f220039fd91',
    messagingSenderId: '660147494084',
    projectId: 'dadnv2',
    authDomain: 'dadnv2.firebaseapp.com',
    storageBucket: 'dadnv2.firebasestorage.app',
    measurementId: 'G-SE9L71P39S',
  );
}
